#!/usr/bin/env bash

if [[ "${CK_LOADGEN_SCENARIO}" == "Offline" ]]; then

  echo "Launching Offline benchmark..."

  if [[ ${KILT_SCHEDULER_YIELD_TIME_OFFLINE:-EMPTY} != "EMPTY" ]]; then export KILT_SCHEDULER_YIELD_TIME=${KILT_SCHEDULER_YIELD_TIME_OFFLINE}; fi
  if [[ ${KILT_DISPATCH_YIELD_TIME_OFFLINE:-EMPTY} != "EMPTY" ]]; then export KILT_DISPATCH_YIELD_TIME=${KILT_DISPATCH_YIELD_TIME_OFFLINE}; fi
  if [[ ${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_OFFLINE:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH=${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_OFFLINE}; fi
  if [[ ${KILT_DEVICE_SCHEDULER_YIELD_TIME_OFFLINE:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_SCHEDULER_YIELD_TIME=${KILT_DEVICE_SCHEDULER_YIELD_TIME_OFFLINE}; fi
  if [[ ${KILT_DEVICE_ENQUEUE_YIELD_TIME_OFFLINE:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_ENQUEUE_YIELD_TIME=${KILT_DEVICE_ENQUEUE_YIELD_TIME_OFFLINE}; fi
  if [[ ${CK_ENV_QAIC_DEVICE_CONFIG_OFFLINE:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DEVICE_CONFIG=${CK_ENV_QAIC_DEVICE_CONFIG_OFFLINE}; fi
  if [[ ${CK_ENV_QAIC_DATASOURCE_CONFIG_OFFLINE:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DATASOURCE_CONFIG=${CK_ENV_QAIC_DATASOURCE_CONFIG_OFFLINE}; fi

elif [ "${CK_LOADGEN_SCENARIO}" == "Server" ]; then

  echo "Launching Server benchmark..."

  if [[ ${KILT_SCHEDULER_YIELD_TIME_SERVER:-EMPTY} != "EMPTY" ]]; then export KILT_SCHEDULER_YIELD_TIME=${KILT_SCHEDULER_YIELD_TIME_SERVER}; fi
  if [[ ${KILT_DISPATCH_YIELD_TIME_SERVER:-EMPTY} != "EMPTY" ]]; then export KILT_DISPATCH_YIELD_TIME=${KILT_DISPATCH_YIELD_TIME_SERVER}; fi
  if [[ ${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_SERVER:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH=${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_SERVER}; fi
  if [[ ${KILT_DEVICE_SCHEDULER_YIELD_TIME_SERVER:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_SCHEDULER_YIELD_TIME=${KILT_DEVICE_SCHEDULER_YIELD_TIME_SERVER}; fi
  if [[ ${KILT_DEVICE_ENQUEUE_YIELD_TIME_SERVER:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_ENQUEUE_YIELD_TIME=${KILT_DEVICE_ENQUEUE_YIELD_TIME_SERVER}; fi
  if [[ ${CK_ENV_QAIC_DEVICE_CONFIG_SERVER:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DEVICE_CONFIG=${CK_ENV_QAIC_DEVICE_CONFIG_SERVER}; fi
  if [[ ${CK_ENV_QAIC_DATASOURCE_CONFIG_SERVER:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DATASOURCE_CONFIG=${CK_ENV_QAIC_DATASOURCE_CONFIG_SERVER}; fi

elif [ "${CK_LOADGEN_SCENARIO}" == "SingleStream" ]; then

  echo "Launching SingleStream benchmark..."

  if [[ ${KILT_SCHEDULER_YIELD_TIME_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_SCHEDULER_YIELD_TIME=${KILT_SCHEDULER_YIELD_TIME_SINGLESTREAM}; fi
  if [[ ${KILT_DISPATCH_YIELD_TIME_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DISPATCH_YIELD_TIME=${KILT_DISPATCH_YIELD_TIME_SINGLESTREAM}; fi
  if [[ ${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH=${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_SINGLESTREAM}; fi
  if [[ ${KILT_DEVICE_SCHEDULER_YIELD_TIME_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_SCHEDULER_YIELD_TIME=${KILT_DEVICE_SCHEDULER_YIELD_TIME_SINGLESTREAM}; fi
  if [[ ${KILT_DEVICE_ENQUEUE_YIELD_TIME_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_ENQUEUE_YIELD_TIME=${KILT_DEVICE_ENQUEUE_YIELD_TIME_SINGLESTREAM}; fi
  if [[ ${CK_ENV_QAIC_DEVICE_CONFIG_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DEVICE_CONFIG=${CK_ENV_QAIC_DEVICE_CONFIG_SINGLESTREAM}; fi
  if [[ ${CK_ENV_QAIC_DATASOURCE_CONFIG_SINGLESTREAM:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DATASOURCE_CONFIG=${CK_ENV_QAIC_DATASOURCE_CONFIG_SINGLESTREAM}; fi

elif [ "${CK_LOADGEN_SCENARIO}" == "MultiStream" ]; then

  echo "Launching MultiStream benchmark..."

  if [[ ${KILT_SCHEDULER_YIELD_TIME_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_SCHEDULER_YIELD_TIME=${KILT_SCHEDULER_YIELD_TIME_MULTISTREAM}; fi
  if [[ ${KILT_DISPATCH_YIELD_TIME_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DISPATCH_YIELD_TIME=${KILT_DISPATCH_YIELD_TIME_MULTISTREAM}; fi
  if [[ ${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH=${KILT_DEVICE_QAIC_SAMPLES_QUEUE_DEPTH_MULTISTREAM}; fi
  if [[ ${KILT_DEVICE_SCHEDULER_YIELD_TIME_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_SCHEDULER_YIELD_TIME=${KILT_DEVICE_SCHEDULER_YIELD_TIME_MULTISTREAM}; fi
  if [[ ${KILT_DEVICE_ENQUEUE_YIELD_TIME_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export KILT_DEVICE_ENQUEUE_YIELD_TIME=${KILT_DEVICE_ENQUEUE_YIELD_TIME_MULTISTREAM}; fi
  if [[ ${CK_ENV_QAIC_DEVICE_CONFIG_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DEVICE_CONFIG=${CK_ENV_QAIC_DEVICE_CONFIG_MULTISTREAM}; fi
  if [[ ${CK_ENV_QAIC_DATASOURCE_CONFIG_MULTISTREAM:-EMPTY} != "EMPTY" ]]; then export CK_ENV_QAIC_DATASOURCE_CONFIG=${CK_ENV_QAIC_DATASOURCE_CONFIG_MULTISTREAM}; fi

else
  echo "Invalid Scenario - exiting."
  exit 1
fi

$1