#! /bin/bash
# CK generated script

if [ "$1" != "1" ]; then if [ "$CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SET" == "1" ]; then return; fi; fi

# Soft UOA           = dataset.object-detection-openimages.preprocessed (4bab9a0191717489)  (dataset,object-detection,preprocessed,openimages,using-various,full,for.retinanet.onnx.preprocessed.quantized,validation,OpenImages,host-os-linux-64,target-os-linux-64,64bits,v1,v1.0)
# Host OS UOA        = linux-64 (4258b5fe54828a50)
# Target OS UOA      = linux-64 (4258b5fe54828a50)
# Target OS bits     = 64
# Tool version       = 1.0
# Tool split version = [1, 0]

# # Dependencies:
# . /home/krai/CK_REPOS/local/env/4816975904f3691e/env.sh
# . /home/krai/CK_REPOS/local/env/cde9eff64a4981d0/env.sh
# . /home/krai/CK_REPOS/local/env/7eb0d7cd207465da/env.sh

export CK_ENV_DATASET_ANNOTATIONS=None
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_CONVERT_DTYPE_BEFORE_RESIZE=0
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_CONVERT_TO_UNSIGNED=0
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_DATA_LAYOUT=NCHW
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_DATA_TYPE=float32
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_DIR=/home/krai/CK-TOOLS/dataset-openimages-preprocessed-using-various-for.retinanet.onnx.preprocessed.quantized-full-openimages-validation
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_GIVEN_CHANNEL_MEANS="0.485 0.456 0.406"
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_GIVEN_CHANNEL_STDS="0.229 0.224 0.225"
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_INPUT_SQUARE_SIDE=800
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_NEW_EXTENSION=rgb8
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_NORMALIZE_DATA=YES
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_NORMALIZE_LOWER=0.0
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_NORMALIZE_UPPER=1.0
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_QUANTIZE=1
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_QUANT_OFFSET=113
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_QUANT_SCALE=0.0185855655
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SUBSET_FOF=original_dimensions.txt
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SUBSET_OFFSET=0
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SUBSET_VOLUME=
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SUBTRACT_MEAN=YES
export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_VALIDATION=YES
export CK_ENV_DATASET_TYPE=None

export CK_ENV_DATASET_OBJ_DETECTION_PREPROCESSED_SET=1
