#! /bin/bash

echo "*** Current CPU frequency from scaling:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq

#echo "*** Current CPU frequency from cpuinfo:"
#sudo cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq

echo "*** Min CPU frequency:"
cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq

echo "*** Max CPU frequency:"
cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq

echo "*** Available CPU frequencies:"
sudo cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_frequencies

echo "*** Current CPU governor:"
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo "*** Available CPU governors:"
sudo cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_available_governors
